"use client";

import React, { useCallback, useMemo, useState } from "react";
import {
  AlertTriangle,
  Download,
  FileJson,
  FileText,
  Loader2,
  Pin,
  PinOff,
  Star,
  TrendingUp,
} from "lucide-react";
import { EDAReport } from "@/lib/types";
import { NarrativeMarkdown } from "@/components/dashboard/AISummarySection";
import { Sparkles } from "lucide-react";

interface Props {
  report: EDAReport;
  fileName?: string;
  aiNarrative?: string | null;
}

/**
 * Flatten the narrative markdown into plain-text lines for PDF/Markdown export.
 * Headings keep their text; bullets become "• "; bold markers are stripped.
 */
function narrativeToPlainLines(narrative: string): { isHeading: boolean; text: string }[] {
  const out: { isHeading: boolean; text: string }[] = [];
  narrative.split("\n").forEach((raw) => {
    const line = raw.trim();
    if (!line) return;
    const heading = line.match(/^#{1,4}\s+(.*)/) || line.match(/^\*\*([^*]+)\*\*:?$/);
    if (heading) {
      out.push({ isHeading: true, text: heading[1].replace(/\*\*/g, "") });
      return;
    }
    const bullet = line.match(/^[-*•]\s+(.*)/) || line.match(/^\d+\.\s+(.*)/);
    const text = (bullet ? `• ${bullet[1]}` : line).replace(/\*\*/g, "");
    out.push({ isHeading: false, text });
  });
  return out;
}

const PINNED_KEY = "sushi_pinned_notes";

function ScoreRing({ score, grade }: { score: number; grade: string }) {
  const radius = 44;
  const circumference = 2 * Math.PI * radius;
  const pct = Math.min(Math.max(score, 0), 100) / 100;
  const dash = circumference * pct;
  const color =
    score >= 80 ? "#22c55e" : score >= 60 ? "#f59e0b" : "#ef4444";

  return (
    <svg width={110} height={110} viewBox="0 0 110 110">
      <circle cx={55} cy={55} r={radius} fill="none" stroke="rgba(0,0,0,0.06)" strokeWidth={10} />
      <circle
        cx={55} cy={55} r={radius} fill="none"
        stroke={color} strokeWidth={10}
        strokeDasharray={`${dash} ${circumference}`}
        strokeLinecap="round"
        transform="rotate(-90 55 55)"
        style={{ transition: "stroke-dasharray 0.8s ease" }}
      />
      <text x={55} y={51} textAnchor="middle" fontSize={20} fontWeight={700} fill={color}>
        {score}
      </text>
      <text x={55} y={65} textAnchor="middle" fontSize={12} fill="#9a9690">
        {grade}
      </text>
    </svg>
  );
}

function MetricCard({ label, value, sub }: { label: string; value: string | number; sub?: string }) {
  return (
    <div style={{
      background: "rgba(255,255,255,0.72)",
      border: "1px solid rgba(0,0,0,0.07)",
      borderRadius: 12, padding: "12px 16px",
    }}>
      <div style={{ fontSize: 20, fontWeight: 700, color: "#111010" }}>{value}</div>
      <div style={{
        fontSize: 10, letterSpacing: "1px", textTransform: "uppercase", color: "#9a9690",
        fontFamily: "ui-monospace, 'Cascadia Code', Menlo, monospace", marginTop: 2,
      }}>{label}</div>
      {sub && <div style={{ fontSize: 11, color: "#9a9690", marginTop: 2 }}>{sub}</div>}
    </div>
  );
}

function generateMarkdown(report: EDAReport, fileName: string, narrative?: string | null): string {
  const { basic_info: info, quality_score: qs, column_analysis: cols, outliers } = report;
  const lines: string[] = [
    `# Data Analysis Report — ${fileName}`,
    `> Generated by Sushi on ${new Date().toLocaleString()}`,
    "",
    ...(narrative ? ["## What Your Data Says", "", narrative, ""] : []),
    "## Dataset Overview",
    `| Metric | Value |`,
    `|---|---|`,
    `| Rows | ${info.rows.toLocaleString()} |`,
    `| Columns | ${info.columns} |`,
    `| Memory | ${info.memory_usage_mb} MB |`,
    `| Duplicates | ${info.duplicate_rows.toLocaleString()} |`,
    `| Missing values | ${info.total_missing.toLocaleString()} |`,
    "",
    "## Quality Score",
    `**Overall: ${qs.overall_score}/100 (Grade ${qs.grade})**`,
    "",
    "| Component | Score |",
    "|---|---|",
    ...Object.entries(qs.breakdown).map(
      ([k, v]) => `| ${k.replace(/_/g, " ")} | ${v.score}/100 |`
    ),
    "",
    ...(qs.recommendations.length > 0
      ? ["### Recommendations", ...qs.recommendations.map((r) => `- ${r}`), ""]
      : []),
    "## Column Summary",
    "| Column | Type | Missing% | Unique |",
    "|---|---|---|---|",
    ...cols.map(
      (c) => `| ${c.name} | ${c.dtype} | ${c.missing_percent}% | ${c.unique_count} |`
    ),
    "",
    ...(outliers.filter((o) => o.outlier_count > 0).length > 0
      ? [
          "## Outliers",
          "| Column | Outliers | % |",
          "|---|---|---|",
          ...outliers
            .filter((o) => o.outlier_count > 0)
            .map((o) => `| ${o.column} | ${o.outlier_count} | ${o.outlier_percent}% |`),
          "",
        ]
      : []),
  ];
  return lines.join("\n");
}

export function ReportSection({ report, fileName = "dataset", aiNarrative }: Props) {
  const { basic_info: info, quality_score: qs, column_analysis: cols, outliers, correlation_matrix } = report;
  const [exporting, setExporting] = useState(false);
  const [pinnedNote, setPinnedNote] = useState<string>(() => {
    try { return localStorage.getItem(PINNED_KEY) ?? ""; } catch { return ""; }
  });
  const [editingNote, setEditingNote] = useState(false);
  const [noteText, setNoteText] = useState(pinnedNote);

  const firingOutliers = useMemo(() => outliers.filter((o) => o.outlier_count > 0), [outliers]);
  const topCorrs = useMemo(() => {
    const pairs: { col1: string; col2: string; r: number }[] = [];
    const { columns, matrix } = correlation_matrix;
    for (let i = 0; i < columns.length; i++) {
      for (let j = i + 1; j < columns.length; j++) {
        const r = matrix[i][j];
        if (!isNaN(r) && Math.abs(r) > 0.5) {
          pairs.push({ col1: columns[i], col2: columns[j], r });
        }
      }
    }
    return pairs.sort((a, b) => Math.abs(b.r) - Math.abs(a.r)).slice(0, 6);
  }, [correlation_matrix]);

  const missingPct = info.total_missing === 0
    ? "0%"
    : `${((info.total_missing / (info.rows * info.columns)) * 100).toFixed(1)}%`;

  function exportMarkdown() {
    const md = generateMarkdown(report, fileName, aiNarrative);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${fileName.replace(/\.[^/.]+$/, "")}_report.md`;
    a.click(); URL.revokeObjectURL(url);
  }

  function exportJSON() {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${fileName.replace(/\.[^/.]+$/, "")}_report.json`;
    a.click(); URL.revokeObjectURL(url);
  }

  const exportPDF = useCallback(async () => {
    setExporting(true);
    try {
      const { default: jsPDF } = await import("jspdf");
      const pdf = new jsPDF("p", "mm", "a4");
      const W = pdf.internal.pageSize.getWidth();
      const H = pdf.internal.pageSize.getHeight();
      const M = 16;
      let y = M;

      const nl = (space = 6) => { y += space; if (y > H - M) { pdf.addPage(); y = M; } };
      const h1 = (text: string) => { pdf.setFontSize(18); pdf.setFont("helvetica", "bold"); pdf.setTextColor(17,16,16); pdf.text(text, M, y); nl(10); };
      const h2 = (text: string) => { nl(4); pdf.setFontSize(13); pdf.setFont("helvetica", "bold"); pdf.setTextColor(17,16,16); pdf.text(text, M, y); nl(7); };
      const body = (text: string, indent = 0) => {
        pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(80,80,80);
        const lines = pdf.splitTextToSize(text, W - 2 * M - indent);
        if (y + lines.length * 4.5 > H - M) { pdf.addPage(); y = M; }
        pdf.text(lines, M + indent, y); nl(lines.length * 4.5 + 1);
      };

      h1(`Sushi Report — ${fileName}`);
      pdf.setFontSize(8); pdf.setTextColor(150,150,150);
      pdf.text(`Generated ${new Date().toLocaleString()}`, M, y); nl(10);

      if (aiNarrative) {
        h2("What Your Data Says");
        narrativeToPlainLines(aiNarrative).forEach(({ isHeading, text }) => {
          if (isHeading) {
            pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(40, 40, 40);
            if (y + 5 > H - M) { pdf.addPage(); y = M; }
            pdf.text(text, M, y); nl(6);
          } else {
            body(text, text.startsWith("•") ? 4 : 0);
          }
        });
      }

      h2("Quality Score");
      body(`Overall: ${qs.overall_score}/100 — Grade ${qs.grade}`);
      Object.entries(qs.breakdown).forEach(([k, v]) => body(`${k.replace(/_/g," ")}: ${v.score}/100`, 4));
      if (qs.recommendations.length) { nl(2); qs.recommendations.forEach((r) => body(`• ${r}`, 4)); }

      h2("Dataset Overview");
      body(`${info.rows.toLocaleString()} rows × ${info.columns} columns | ${info.memory_usage_mb} MB | ${info.duplicate_rows} duplicates | ${missingPct} missing`);

      h2("Column Summary");
      cols.slice(0, 20).forEach((c) => body(`${c.name} [${c.dtype}]  missing ${c.missing_percent}%  unique ${c.unique_count}`, 4));

      if (topCorrs.length) {
        h2("Strong Correlations");
        topCorrs.forEach(({ col1, col2, r }) => body(`${col1} ↔ ${col2}: r = ${r.toFixed(3)}`, 4));
      }

      if (firingOutliers.length) {
        h2("Outliers");
        firingOutliers.slice(0, 10).forEach((o) => body(`${o.column}: ${o.outlier_count} outliers (${o.outlier_percent}%)`, 4));
      }

      pdf.setFontSize(7); pdf.setTextColor(180,180,180);
      pdf.text("Generated by Sushi — sushi-eda.vercel.app", W / 2, H - 8, { align: "center" });

      pdf.save(`${fileName.replace(/\.[^/.]+$/, "")}_sushi_report.pdf`);
    } finally {
      setExporting(false);
    }
  }, [fileName, qs, info, cols, topCorrs, firingOutliers, missingPct, aiNarrative]);

  function saveNote() {
    try { localStorage.setItem(PINNED_KEY, noteText); } catch {}
    setPinnedNote(noteText);
    setEditingNote(false);
  }

  return (
    <div style={{ padding: "24px 32px", maxWidth: 900, margin: "0 auto" }}>
      {/* Header */}
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 28 }}>
        <div>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111010", margin: 0 }}>Report</h2>
          <p style={{ fontSize: 13, color: "#9a9690", margin: "4px 0 0" }}>
            {fileName} · {new Date().toLocaleDateString()}
          </p>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button onClick={exportMarkdown} style={btnStyle("ghost")}>
            <FileText size={13} /> Markdown
          </button>
          <button onClick={exportJSON} style={btnStyle("ghost")}>
            <FileJson size={13} /> JSON
          </button>
          <button onClick={exportPDF} disabled={exporting} style={btnStyle("primary")}>
            {exporting ? <Loader2 size={13} style={{ animation: "spin 1s linear infinite" }} /> : <Download size={13} />}
            {exporting ? "Exporting…" : "Export PDF"}
          </button>
        </div>
      </div>

      {/* Quality score + key metrics */}
      <div style={{ display: "flex", gap: 20, marginBottom: 24, alignItems: "center" }}>
        <div style={{
          background: "rgba(255,255,255,0.72)",
          border: "1px solid rgba(0,0,0,0.07)",
          borderRadius: 16, padding: "20px 24px",
          display: "flex", flexDirection: "column", alignItems: "center", gap: 6,
          flexShrink: 0,
        }}>
          <ScoreRing score={qs.overall_score} grade={qs.grade} />
          <span style={{
            fontSize: 9, letterSpacing: "1.5px", textTransform: "uppercase",
            color: "#9a9690", fontFamily: "ui-monospace, 'Cascadia Code', Menlo, monospace",
          }}>Quality score</span>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, flex: 1 }}>
          <MetricCard label="Rows" value={info.rows.toLocaleString()} />
          <MetricCard label="Columns" value={info.columns} />
          <MetricCard label="Missing" value={missingPct} sub={`${info.total_missing.toLocaleString()} cells`} />
          <MetricCard label="Duplicates" value={info.duplicate_rows.toLocaleString()} />
        </div>
      </div>

      {/* AI summary — leads the report */}
      {aiNarrative && (
        <Section title="What your data says" icon={<Sparkles size={14} style={{ color: "#9060f8" }} />}>
          <NarrativeMarkdown text={aiNarrative} />
        </Section>
      )}

      {/* Recommendations */}
      {qs.recommendations.length > 0 && (
        <Section title="Recommendations" icon={<Star size={14} style={{ color: "#f59e0b" }} />}>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {qs.recommendations.map((r, i) => (
              <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 8 }}>
                <span style={{ color: "#f59e0b", marginTop: 1, flexShrink: 0 }}>•</span>
                <span style={{ fontSize: 13, color: "#4b4540" }}>{r}</span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Strong correlations */}
      {topCorrs.length > 0 && (
        <Section title="Strong Correlations" icon={<TrendingUp size={14} style={{ color: "#9060f8" }} />}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 8 }}>
            {topCorrs.map(({ col1, col2, r }) => (
              <div key={`${col1}-${col2}`} style={{
                background: "rgba(144,96,248,0.05)", border: "1px solid rgba(144,96,248,0.12)",
                borderRadius: 8, padding: "8px 12px", display: "flex", justifyContent: "space-between", alignItems: "center",
              }}>
                <span style={{ fontSize: 12, color: "#4b4540" }}>{col1} ↔ {col2}</span>
                <span style={{
                  fontWeight: 700, fontSize: 13,
                  color: r > 0 ? "#9060f8" : "#ef4444",
                  fontFamily: "ui-monospace, 'Cascadia Code', Menlo, monospace",
                }}>
                  {r > 0 ? "+" : ""}{r.toFixed(3)}
                </span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Outliers */}
      {firingOutliers.length > 0 && (
        <Section title="Outlier Flags" icon={<AlertTriangle size={14} style={{ color: "#ef4444" }} />}>
          <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
            {firingOutliers.slice(0, 10).map((o) => (
              <div key={o.column} style={{ display: "flex", alignItems: "center", gap: 10, fontSize: 12 }}>
                <span style={{ fontWeight: 600, color: "#111010", minWidth: 120 }}>{o.column}</span>
                <span style={{ color: "#ef4444", fontFamily: "ui-monospace, 'Cascadia Code', Menlo, monospace" }}>
                  {o.outlier_count} outliers ({o.outlier_percent}%)
                </span>
                <span style={{ color: "#9a9690" }}>bounds [{o.lower_bound.toFixed(2)}, {o.upper_bound.toFixed(2)}]</span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Column quality breakdown */}
      <Section title="Column Quality">
        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
            <thead>
              <tr style={{ borderBottom: "1px solid rgba(0,0,0,0.08)" }}>
                {["Column", "Type", "Missing", "Unique", "Status"].map((h) => (
                  <th key={h} style={{
                    textAlign: "left", padding: "6px 10px",
                    fontSize: 9, letterSpacing: "1px", textTransform: "uppercase",
                    color: "#9a9690", fontFamily: "ui-monospace, 'Cascadia Code', Menlo, monospace",
                    fontWeight: 600,
                  }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {cols.map((c) => (
                <tr key={c.name} style={{ borderBottom: "1px solid rgba(0,0,0,0.04)" }}>
                  <td style={{ padding: "6px 10px", fontWeight: 500, color: "#111010" }}>{c.name}</td>
                  <td style={{ padding: "6px 10px", color: "#9a9690", fontFamily: "ui-monospace, 'Cascadia Code', Menlo, monospace", fontSize: 11 }}>{c.dtype}</td>
                  <td style={{ padding: "6px 10px", color: c.missing_percent > 20 ? "#ef4444" : c.missing_percent > 5 ? "#f59e0b" : "#22c55e" }}>
                    {c.missing_percent}%
                  </td>
                  <td style={{ padding: "6px 10px", color: "#9a9690" }}>{c.unique_count.toLocaleString()}</td>
                  <td style={{ padding: "6px 10px" }}>
                    <span style={{
                      display: "inline-block", padding: "1px 7px", borderRadius: 20, fontSize: 10,
                      background: c.missing_percent === 0 ? "rgba(34,197,94,0.1)" : c.missing_percent > 20 ? "rgba(239,68,68,0.1)" : "rgba(245,158,11,0.1)",
                      color: c.missing_percent === 0 ? "#22c55e" : c.missing_percent > 20 ? "#ef4444" : "#f59e0b",
                    }}>
                      {c.missing_percent === 0 ? "clean" : c.missing_percent > 20 ? "high missing" : "some missing"}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      {/* Analyst notes (pinned) */}
      <Section title="Analyst Notes" icon={<Pin size={14} style={{ color: "#9060f8" }} />}>
        {editingNote ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            <textarea
              value={noteText}
              onChange={(e) => setNoteText(e.target.value)}
              rows={4}
              placeholder="Add notes, observations, or next steps…"
              style={{
                width: "100%", padding: "10px 12px", borderRadius: 8,
                border: "1px solid rgba(144,96,248,0.3)", fontSize: 13,
                color: "#111010", background: "rgba(255,255,255,0.9)",
                resize: "vertical", outline: "none", boxSizing: "border-box",
              }}
            />
            <div style={{ display: "flex", gap: 8 }}>
              <button onClick={saveNote} style={btnStyle("primary")}>Save</button>
              <button onClick={() => { setEditingNote(false); setNoteText(pinnedNote); }} style={btnStyle("ghost")}>Cancel</button>
            </div>
          </div>
        ) : (
          <div>
            {pinnedNote ? (
              <p style={{ fontSize: 13, color: "#4b4540", whiteSpace: "pre-wrap", marginBottom: 10 }}>{pinnedNote}</p>
            ) : (
              <p style={{ fontSize: 13, color: "#9a9690", marginBottom: 10 }}>No notes yet. Add observations or next steps.</p>
            )}
            <button onClick={() => { setEditingNote(true); setNoteText(pinnedNote); }} style={btnStyle("ghost")}>
              {pinnedNote ? <><PinOff size={12} /> Edit notes</> : <><Pin size={12} /> Add notes</>}
            </button>
          </div>
        )}
      </Section>

      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}

function Section({ title, icon, children }: { title: string; icon?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div style={{
      background: "rgba(255,255,255,0.72)",
      border: "1px solid rgba(0,0,0,0.07)",
      borderRadius: 14, overflow: "hidden", marginBottom: 16,
    }}>
      <div style={{
        height: 3,
        background: "linear-gradient(90deg, #9060f8, #e840c8, #00d4e8, #9060f8)",
        backgroundSize: "200% 100%",
        animation: "shimmer 4s linear infinite",
      }} />
      <div style={{ padding: "14px 18px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 12 }}>
          {icon}
          <span style={{
            fontSize: 9, letterSpacing: "1.5px", textTransform: "uppercase",
            color: "#9a9690", fontFamily: "ui-monospace, 'Cascadia Code', Menlo, monospace",
            fontWeight: 600,
          }}>{title}</span>
        </div>
        {children}
      </div>
      <style>{`@keyframes shimmer { 0% { background-position: 0% 0; } 100% { background-position: 200% 0; } }`}</style>
    </div>
  );
}

function btnStyle(variant: "primary" | "ghost") {
  const base: React.CSSProperties = {
    display: "inline-flex", alignItems: "center", gap: 5,
    padding: "7px 14px", borderRadius: 8, fontSize: 12,
    fontWeight: 600, cursor: "pointer", border: "none",
  };
  return variant === "primary"
    ? { ...base, background: "linear-gradient(135deg, #9060f8, #e840c8)", color: "#fff" }
    : { ...base, background: "rgba(0,0,0,0.05)", color: "#6b6860" };
}
