"""Baseline: core schema (organizations, users, org_members, datasets, analyses, feedback)

This replaces the pre-remodel migration chain (001–004), which was deleted
along with the monitors/pipelines/connectors/comments features. Fresh
databases start here; the demo-mode SQLite fallback doesn't use Alembic at
all (main.py runs create_all at startup).

Revision ID: 100_baseline
Revises:
Create Date: 2026-07-03
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "100_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # create_all is idempotent (checkfirst) and always mirrors db/models.py.
    # Future schema changes should be proper autogenerated revisions on top.
    from db.models import Base

    Base.metadata.create_all(bind=op.get_bind(), checkfirst=True)


def downgrade() -> None:
    from db.models import Base

    Base.metadata.drop_all(bind=op.get_bind())
