"use client";

import React, { useCallback, useMemo, useState } from "react";
import {
  AlertTriangle,
  Download,
  FileJson,
  FileText,
  Loader2,
  Pin,
  PinOff,
  Star,
  TrendingUp,
} from "lucide-react";
import { EDAReport } from "@/lib/types";
import { NarrativeMarkdown } from "@/components/dashboard/AISummarySection";
import { exportReportPDF } from "@/lib/pdfExport";
import { HankoStamp } from "@/components/sushi/HankoStamp";
import { cn } from "@/lib/utils";
import { Sparkles } from "lucide-react";

interface Props {
  report: EDAReport;
  fileName?: string;
  aiNarrative?: string | null;
}

const PINNED_KEY = "sushi_pinned_notes";

function stampTone(score: number): "wasabi" | "salmon" | "tuna" {
  if (score >= 80) return "wasabi";
  if (score >= 60) return "salmon";
  return "tuna";
}

function MetricCard({ label, value, sub }: { label: string; value: string | number; sub?: string }) {
  return (
    <div className="rounded-xl border border-line bg-surface px-4 py-3">
      <div className="text-[20px] font-bold text-ink">{value}</div>
      <div className="mt-0.5 font-mono text-[10px] uppercase tracking-[1px] text-muted-ink">{label}</div>
      {sub && <div className="mt-0.5 text-[11px] text-muted-ink">{sub}</div>}
    </div>
  );
}

function generateMarkdown(report: EDAReport, fileName: string, narrative?: string | null): string {
  const { basic_info: info, quality_score: qs, column_analysis: cols, outliers } = report;
  const lines: string[] = [
    `# Data Analysis Report — ${fileName}`,
    `> Generated by Sushi on ${new Date().toLocaleString()}`,
    "",
    ...(narrative ? ["## What Your Data Says", "", narrative, ""] : []),
    "## Dataset Overview",
    `| Metric | Value |`,
    `|---|---|`,
    `| Rows | ${info.rows.toLocaleString()} |`,
    `| Columns | ${info.columns} |`,
    `| Memory | ${info.memory_usage_mb} MB |`,
    `| Duplicates | ${info.duplicate_rows.toLocaleString()} |`,
    `| Missing values | ${info.total_missing.toLocaleString()} |`,
    "",
    "## Quality Score",
    `**Overall: ${qs.overall_score}/100 (Grade ${qs.grade})**`,
    "",
    "| Component | Score |",
    "|---|---|",
    ...Object.entries(qs.breakdown).map(
      ([k, v]) => `| ${k.replace(/_/g, " ")} | ${v.score}/100 |`
    ),
    "",
    ...(qs.recommendations.length > 0
      ? ["### Recommendations", ...qs.recommendations.map((r) => `- ${r}`), ""]
      : []),
    "## Column Summary",
    "| Column | Type | Missing% | Unique |",
    "|---|---|---|---|",
    ...cols.map(
      (c) => `| ${c.name} | ${c.dtype} | ${c.missing_percent}% | ${c.unique_count} |`
    ),
    "",
    ...(outliers.filter((o) => o.outlier_count > 0).length > 0
      ? [
          "## Outliers",
          "| Column | Outliers | % |",
          "|---|---|---|",
          ...outliers
            .filter((o) => o.outlier_count > 0)
            .map((o) => `| ${o.column} | ${o.outlier_count} | ${o.outlier_percent}% |`),
          "",
        ]
      : []),
  ];
  return lines.join("\n");
}

export function ReportSection({ report, fileName = "dataset", aiNarrative }: Props) {
  const { basic_info: info, quality_score: qs, column_analysis: cols, outliers, correlation_matrix } = report;
  const [exporting, setExporting] = useState(false);
  const [pinnedNote, setPinnedNote] = useState<string>(() => {
    try { return localStorage.getItem(PINNED_KEY) ?? ""; } catch { return ""; }
  });
  const [editingNote, setEditingNote] = useState(false);
  const [noteText, setNoteText] = useState(pinnedNote);

  const firingOutliers = useMemo(() => outliers.filter((o) => o.outlier_count > 0), [outliers]);
  const topCorrs = useMemo(() => {
    const pairs: { col1: string; col2: string; r: number }[] = [];
    const { columns, matrix } = correlation_matrix;
    for (let i = 0; i < columns.length; i++) {
      for (let j = i + 1; j < columns.length; j++) {
        const r = matrix[i][j];
        if (!isNaN(r) && Math.abs(r) > 0.5) {
          pairs.push({ col1: columns[i], col2: columns[j], r });
        }
      }
    }
    return pairs.sort((a, b) => Math.abs(b.r) - Math.abs(a.r)).slice(0, 6);
  }, [correlation_matrix]);

  const missingPct = info.total_missing === 0
    ? "0%"
    : `${((info.total_missing / (info.rows * info.columns)) * 100).toFixed(1)}%`;

  function exportMarkdown() {
    const md = generateMarkdown(report, fileName, aiNarrative);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${fileName.replace(/\.[^/.]+$/, "")}_report.md`;
    a.click(); URL.revokeObjectURL(url);
  }

  function exportJSON() {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${fileName.replace(/\.[^/.]+$/, "")}_report.json`;
    a.click(); URL.revokeObjectURL(url);
  }

  const exportPDF = useCallback(async () => {
    setExporting(true);
    try {
      await exportReportPDF(report, fileName, aiNarrative);
    } finally {
      setExporting(false);
    }
  }, [report, fileName, aiNarrative]);

  function saveNote() {
    try { localStorage.setItem(PINNED_KEY, noteText); } catch {}
    setPinnedNote(noteText);
    setEditingNote(false);
  }

  return (
    <div className="mx-auto max-w-[900px] px-8 py-6">
      {/* Header */}
      <div className="mb-7 flex items-start justify-between">
        <div>
          <h2 className="text-[20px] font-bold text-ink">Report</h2>
          <p className="mt-1 text-[13px] text-muted-ink">
            {fileName} · {new Date().toLocaleDateString()}
          </p>
        </div>
        <div className="flex gap-2">
          <button onClick={exportMarkdown} className={ghostBtn}>
            <FileText size={13} /> Markdown
          </button>
          <button onClick={exportJSON} className={ghostBtn}>
            <FileJson size={13} /> JSON
          </button>
          <button onClick={exportPDF} disabled={exporting} className={primaryBtn}>
            {exporting ? <Loader2 size={13} className="animate-spin" /> : <Download size={13} />}
            {exporting ? "Exporting…" : "Export PDF"}
          </button>
        </div>
      </div>

      {/* Quality score + key metrics */}
      <div className="mb-6 flex items-center gap-5">
        <div className="flex shrink-0 flex-col items-center gap-1.5 rounded-card border border-line bg-surface px-6 py-5">
          <HankoStamp value={qs.overall_score} label={`Grade ${qs.grade}`} tone={stampTone(qs.overall_score)} size={100} rotation={-8} />
        </div>

        <div className="grid flex-1 grid-cols-2 gap-2.5">
          <MetricCard label="Rows" value={info.rows.toLocaleString()} />
          <MetricCard label="Columns" value={info.columns} />
          <MetricCard label="Missing" value={missingPct} sub={`${info.total_missing.toLocaleString()} cells`} />
          <MetricCard label="Duplicates" value={info.duplicate_rows.toLocaleString()} />
        </div>
      </div>

      {/* AI summary — leads the report */}
      {aiNarrative && (
        <Section title="What your data says" icon={<Sparkles size={14} className="text-brand" />}>
          <NarrativeMarkdown text={aiNarrative} />
        </Section>
      )}

      {/* Recommendations */}
      {qs.recommendations.length > 0 && (
        <Section title="Recommendations" icon={<Star size={14} className="text-warning" />}>
          <div className="flex flex-col gap-1.5">
            {qs.recommendations.map((r, i) => (
              <div key={i} className="flex items-start gap-2">
                <span className="mt-px shrink-0 text-warning">•</span>
                <span className="text-[13px] text-ink/80">{r}</span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Strong correlations */}
      {topCorrs.length > 0 && (
        <Section title="Strong Correlations" icon={<TrendingUp size={14} className="text-brand" />}>
          <div className="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-2">
            {topCorrs.map(({ col1, col2, r }) => (
              <div key={`${col1}-${col2}`} className="flex items-center justify-between rounded-lg border border-brand/[0.12] bg-brand-weak px-3 py-2">
                <span className="text-[12px] text-ink/80">{col1} ↔ {col2}</span>
                <span className={cn("font-mono text-[13px] font-bold", r > 0 ? "text-brand" : "text-danger")}>
                  {r > 0 ? "+" : ""}{r.toFixed(3)}
                </span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Outliers */}
      {firingOutliers.length > 0 && (
        <Section title="Outlier Flags" icon={<AlertTriangle size={14} className="text-danger" />}>
          <div className="flex flex-col gap-1">
            {firingOutliers.slice(0, 10).map((o) => (
              <div key={o.column} className="flex items-center gap-2.5 text-[12px]">
                <span className="min-w-[120px] font-semibold text-ink">{o.column}</span>
                <span className="font-mono text-danger">
                  {o.outlier_count} outliers ({o.outlier_percent}%)
                </span>
                <span className="text-muted-ink">bounds [{o.lower_bound.toFixed(2)}, {o.upper_bound.toFixed(2)}]</span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Column quality breakdown */}
      <Section title="Column Quality">
        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-[12px]">
            <thead>
              <tr className="border-b border-line">
                {["Column", "Type", "Missing", "Unique", "Status"].map((h) => (
                  <th key={h} className="px-2.5 py-1.5 text-left font-mono text-[9px] font-semibold uppercase tracking-[1px] text-muted-ink">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {cols.map((c) => (
                <tr key={c.name} className="border-b border-line/60">
                  <td className="px-2.5 py-1.5 font-medium text-ink">{c.name}</td>
                  <td className="px-2.5 py-1.5 font-mono text-[11px] text-muted-ink">{c.dtype}</td>
                  <td
                    className={cn(
                      "px-2.5 py-1.5",
                      c.missing_percent > 20 ? "text-danger" : c.missing_percent > 5 ? "text-warning" : "text-success",
                    )}
                  >
                    {c.missing_percent}%
                  </td>
                  <td className="px-2.5 py-1.5 text-muted-ink">{c.unique_count.toLocaleString()}</td>
                  <td className="px-2.5 py-1.5">
                    <span
                      className={cn(
                        "inline-block rounded-pill px-1.5 py-px text-[10px]",
                        c.missing_percent === 0
                          ? "bg-success/10 text-success"
                          : c.missing_percent > 20
                            ? "bg-danger/10 text-danger"
                            : "bg-warning/10 text-warning",
                      )}
                    >
                      {c.missing_percent === 0 ? "clean" : c.missing_percent > 20 ? "high missing" : "some missing"}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      {/* Analyst notes (pinned) */}
      <Section title="Analyst Notes" icon={<Pin size={14} className="text-brand" />}>
        {editingNote ? (
          <div className="flex flex-col gap-2">
            <textarea
              value={noteText}
              onChange={(e) => setNoteText(e.target.value)}
              rows={4}
              placeholder="Add notes, observations, or next steps…"
              className="w-full resize-y rounded-lg border border-brand/30 bg-surface px-3 py-2.5 text-[13px] text-ink outline-none"
            />
            <div className="flex gap-2">
              <button onClick={saveNote} className={primaryBtn}>Save</button>
              <button onClick={() => { setEditingNote(false); setNoteText(pinnedNote); }} className={ghostBtn}>Cancel</button>
            </div>
          </div>
        ) : (
          <div>
            {pinnedNote ? (
              <p className="mb-2.5 whitespace-pre-wrap text-[13px] text-ink/80">{pinnedNote}</p>
            ) : (
              <p className="mb-2.5 text-[13px] text-muted-ink">No notes yet. Add observations or next steps.</p>
            )}
            <button onClick={() => { setEditingNote(true); setNoteText(pinnedNote); }} className={ghostBtn}>
              {pinnedNote ? <><PinOff size={12} /> Edit notes</> : <><Pin size={12} /> Add notes</>}
            </button>
          </div>
        )}
      </Section>
    </div>
  );
}

const ghostBtn = "inline-flex items-center gap-1.5 rounded-lg bg-ink/5 px-3.5 py-1.5 text-[12px] font-semibold text-muted-ink";
const primaryBtn = "inline-flex items-center gap-1.5 rounded-lg bg-[linear-gradient(135deg,var(--salmon),var(--tuna))] px-3.5 py-1.5 text-[12px] font-semibold text-white";

function Section({ title, icon, children }: { title: string; icon?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="mb-4 overflow-hidden rounded-2xl border border-line bg-surface">
      <div className="h-[3px] bg-[linear-gradient(90deg,var(--salmon),var(--tuna),var(--wasabi),var(--salmon))] bg-[length:200%_100%] [animation:sushiShimmer_4s_linear_infinite]" />
      <div className="px-[18px] py-3.5">
        <div className="mb-3 flex items-center gap-1.5">
          {icon}
          <span className="font-mono text-[9px] font-semibold uppercase tracking-[1.5px] text-muted-ink">{title}</span>
        </div>
        {children}
      </div>
    </div>
  );
}
